### ISSUE TITLE
compatible

### ISSUE THREAD

**Issue by hasanelfalakiy** [fwcd/kola#1]
I want to ask, can this Kola Kotlin LSP be used in Sora Editor / for Android applications?

**Comment by fwcd** [comment]
Sure, if they've got an LSP client, I don't see why not

**Comment by hasanelfalakiy** [comment]
> Sure, if they've got an LSP client, I don't see why not

oh great, I hope kola can be used optimally in sora editor

Look at this, I don't know if I'm showing it right

https://github.com/Rosemoe/sora-editor/tree/main/editor-lsp%2Fsrc%2Fmain%2Fjava%2Fio%2Fgithub%2Frosemoe%2Fsora%2Flsp

**Comment by fwcd** [comment]
Closing this since integration with specific LSP clients is outside of the scope of this project (also it's highly experimental at this point). Kola doesn't do anything non-standard, so if Sora Editor is LSP-compliant, it should just work out of the box (though I'm not familiar with building Rust for Android, so you might have to look that up).
